toss/react-simplikit

src/docs/ko/intro.md
Hello toss!
Congratulations on your new open source project!
=> docs: fix typo

eslint.config.mjs, package.json, yarn.lock
* Same with https://github.com/toss/suspensive/pull/1476
=> chore(eslint): update 'eslint-plugin-react-hooks' config to use 'recommended-latest' 

eslint.config.mjs
* Like `**/dist/**`, add `**/esm/**`
=> chore(eslint): add '**/esm/**' in ignores

eslint.config.js
* Like `simpleImportSort`, `unusedImports`, simplify and clarify import name
=> chore(eslint): simplify and clarify import name

.github/workflows/deployment.yml, .github/workflows/integration.yml
=> ci(.github/workflows): add caching 'yarn' in 'actions/setup-node'

src/hooks/useOutsideClickEffect/ko/useOutsideClickEffect.md
=> docs(ko/useOutsideClickEffect): replace 'React' with Korean '리액트'

.vitepress/ko.mts
update untranslated sidebar menu
=> docs(ko): update untranslated sidebar menu

src/hooks/useBooleanState/useBooleanState.ts
=> refactor(useBooleanState): clarify 'setBool' updater param in 'toggle'

src/hooks/useBooleanState/useBooleanState.ts
=> refactor(useBooleanState): convert arrow function to function declaration

.github/workflows/deployment.yml
* relate https://github.com/toss/react-simplikit/pull/169
=> ci(.github/workflows/development): add 'fix:format' script in 'Generate docs'

src/docs/en/intro.md, src/docs/ko/intro.md
fix intro.md typo
without -> with
=> docs(docs/**/intro): fix typo

src/hooks/useStorageState/useStorageState.spec.ts, src/hooks/useStorageState/useStorageState.ts, vitest.config.ts
=> feat(useStorageState). update useStorageState to return refresh and can use custom serializer

.scripts/index.ts
=> chore(.script): align with the 'Scaffolding' section in the 'contributing.md'

.github/workflows/integration.yml
=> ci(.github/workflows/integration): fix formatting by adding missing space

src/docs/en/installation.md, src/docs/ko/installation.md
- match documents in two different languages.
- combine unnecessarily divided sections into one.
=> docs(installation): update Korean and English documents

.github/pull_request_template.md
=> docs(.github/pull_request_template): replace 'yarn test:coverage' with 'yarn run test:coverage'

.scripts/commands/generateDocs/index.ts
=> chore(generateDocs): remove unused 'catch' param

.github/pull_request_template.md
=> docs(.github/pull_request_template): add checklist for running 'yarn run fix'

src/hooks/useThrottle/throttle.ts, src/hooks/useThrottle/useThrottle.spec.ts
=> fix(useThrottle): fix useThrottle with both leading and trailing

.github/workflows/deployment.yml
=> ci(.github/workflows/deployment): add 'chore' prefix to version bump commit message

README.md
=> docs(README): add discord badge

tsup.config.ts
I add a use client directive in `src/index.ts` for rsc compatibility
no error occured when using like this
```
import { ImpressionArea } from 'react-simplikit';
export default function Page() {
return (
<ImpressionArea timeThreshold={1000} areaThreshold={0.5}>
<div>React Simplikit Test</div>
</ImpressionArea>
);
}
```
=> feat(src/index.ts): add 'use client' directive for RSC compatibility
