toss/react-simplikit

.pnp.cjs
package.json

Move OpenAI package from dependencies to devDependencies since it's only used in development environment.

chore: move openai to devDependencies

---

.github/workflows/integration.yml
README-ko_kr.md
README.md
codecov.yml

Same with https://github.com/toss/es-toolkit/pull/34
1. Please add the Codecov GitHub bot: https://github.com/apps/codecov
From now on, it will check changes via comments, and if the target test coverage (set at 90%, goal: 100%, threshold: 10%) is not met, it will block with an X in the GitHub status check. This will motivate contributors to write test codes and allow maintainers to quickly identify test coverage impacts from changes.
2. The organization and this repository need to be registered with Codecov.
Once this PR is merged, it will be set up and start tracking coverage.
3. Before merging, a CODECOV_TOKEN for upload needs to be added.
A token is required for uploads.

ci(codecov): setup

---

src/docs/en/intro.md
src/docs/ko/intro.md

This PR fixes errors in the Separated component example in the introduction documentation.
- Corrected the Separated component example code in the introduction docs
- Removed unnecessary nested mapping of the 'texts' array
- Added missing closing parentheses
- Improved readability and accuracy of the code example
- Applied the same fixes to both Korean (ko) and English (en) documentation
The previous example did not correctly demonstrate the proper usage of the Separated component and contained syntax errors. This fix ensures users can understand the intended usage of the component correctly.

docs: Fix Separated component example in introduction documentation

---

src/docs/en/intro.md
src/docs/ko/intro.md

This PR fixes the separator logic in the example code to correctly demonstrate how to implement separators between list items.
- Updated the conditional logic in the example code to correctly place separators between list items.
We considered three approaches to fix the separator logic:
1. Using `idx !== texts.length - 1` condition
2. Using `idx < texts.length - 1` condition
3. Keeping `idx === texts.length - 1` condition but reversing the ternary operator
After careful consideration, we chose the second approach (`idx < texts.length - 1`) as the optimal solution for the following reasons:
- It clearly expresses the intent to show the Border from the first element up to, but not including, the last element
- It's a common idiomatic expression when dealing with array indices
- It's more …

docs: Fix separator logic in example code

---

eslint.config.mjs

* With addding `tsup.*` in ignores, we can fix this problem.

chore(eslint): add 'tsup.*' in ignores

---

.scripts/commands/generateDocs/index.ts

chore(.scripts/commands/generateDocs): disable eslint 'unused-imports/no-unused-vars' warning

---

.vitepress/en.mts
.vitepress/ko.mts
src/docs/en/index.md
src/docs/ko/index.md

Fix the reference link in the header and navigation so that it now navigates to `components/ImpressionArea.html` at the top level instead of `hooks/useBooleanState.html`.

docs: update link for 'Reference'

---

src/hooks/useAsyncEffect/ko/useAsyncEffect.md
src/hooks/useAsyncEffect/useAsyncEffect.md

This PR addresses two issues in the useAsyncEffect documentation:
1. Corrects the description of the effect's behavior when the dependency array is omitted.
Previously, it incorrectly stated that the effect would run only once when the component mounts.
The correct behavior is that the effect runs on every re-render when deps are omitted.
This is evidenced by the following test case:
```ts
it('should call effect every rerender when deps are undefined', async () => {
const effect = vi.fn().mockResolvedValue(undefined);
const { rerender } = await renderHookSSR(() => useAsyncEffect(effect));
await flushPromises();
expect(effect).toHaveBeenCalled();
rerender();
expect(effect).toHaveBeenCalledTimes(2);
rerender();
expect(effect).toHaveBeenCalledTimes(3);
});
```
2. Improves consistency in …

docs: useAsyncEffect documentation Clarify behavior when deps are omitted

---

src/hooks/useStorageState/useStorageState.ts

* The variable name value in the `setStorageState` function of the `useStorageState` hook has been changed to `nextValue`. This change is made to align with React’s `setState` pattern.
* In `setState`, the parameter passed is typically named `nextValue`, following the naming convention used in the function update pattern.
* The name value represents the value being handled inside `setStorageState`, and renaming it to `nextValue` ensures consistency with React’s `useState` and `setState` functions.

refactor(useStorageState): rename param 'value' to 'nextValue' in 'setStorageState'

---

.prettierrc
.scripts/commands/generateDocs/index.ts

* In `generateDoc`, the document is generated using `prettier.format` with the default config, To ensure consistency across the code, adding our `.prettierrc` config in `prettier.format` in `.script/commands/generateDocs/index.ts`. This could help resolve issues like https://github.com/toss/react-simplikit/pull/123#issuecomment-2799779862.
* About the result of `generateDoc`, we need to check it

chore(*): unify the format of '.prettierrc' and the result of 'generateDocs'

---

.prettierignore
.vitepress/components/SplitView.vue
src/docs/en/intro.md

add scroll button and fix gradient
https://github.com/user-attachments/assets/c4270788-0d3c-4cdf-b934-eed5b1faf241

docs(*). enhance SplitView

---

.prettierignore
.prettierrc
src/docs/en/intro.md
src/docs/ko/intro.md

* relate https://github.com/toss/react-simplikit/pull/173
* relate https://github.com/toss/react-simplikit/pull/123#issuecomment-2799779862
* `intro.md`s are applyed by `prettier`

docs(docs/**/intro): unify kr and en docs, add printWidth to 70 in '**/intro.md' in '.prettierrc'

---

src/hooks/useThrottle/useThrottle.ts

docs(useThrottle.ts): add missing '*' in JSDoc

---

src/docs/en/why-react-simplikit-matters.md
src/docs/ko/why-react-simplikit-matters.md

- update invalid links
- update to the correct bundle size
- set `react-use` to have [115 functions](https://www.npmjs.com/package/react-use) in it.
- set `react-simplikit` to have 28 functions. (see sidebar in the [documentation](https://react-simplikit.slash.page/))

docs: update bundle size section

---

src/hooks/useCounter/index.ts
src/hooks/useCounter/ko/useCounter.md
src/hooks/useCounter/useCounter.md
src/hooks/useCounter/useCounter.spec.ts
src/hooks/useCounter/useCounter.ts
src/index.ts

Add `useCounter` hook: `useCounter` is a React hook that manages a numeric counter state with increment, decrement, and reset capabilities. Optionally, you can provide minimum and maximum values to constrain the counter's range.

feat(useCounter): add useCounter hook

---

src/docs/en/why-react-simplikit-matters.md
src/docs/ko/why-react-simplikit-matters.md

style(docs): apply 'prettier --write .'

---

src/components/SwitchCase/SwitchCase.md
src/components/SwitchCase/SwitchCase.tsx
src/components/SwitchCase/ko/SwitchCase.md

SwitchCase 의 value에 boolean이 실제로 사용 가능한데 문서와 타입 정의에는 빠져있어서 추가했습니다.

docs(SwitchCase): add 'boolean' type

---

src/docs/en/intro.md
src/docs/en/why-react-simplikit-matters.md
src/docs/ko/intro.md
src/docs/ko/why-react-simplikit-matters.md

- add missing inline code
- rename state update function
- update unnatural Korean translation

docs: update code example and some contents

---

.vitepress/theme/style.css
src/docs/en/contributing.md
src/docs/ko/contributing.md

- update the background color of codeblocks to improve readability.
- add missing inline code.

style: update background colors of codeblocks

---

src/hooks/useAsyncEffect/useAsyncEffect.md
src/hooks/useAsyncEffect/useAsyncEffect.ts
src/hooks/useCallbackOncePerRender/useCallbackOncePerRender.md
src/hooks/useCallbackOncePerRender/useCallbackOncePerRender.ts
src/hooks/useControlledState/useControlledState.md
src/hooks/useControlledState/useControlledState.ts
src/hooks/useDebouncedCallback/useDebouncedCallback.md
src/hooks/useDebouncedCallback/useDebouncedCallback.ts
src/hooks/useImpressionRef/useImpressionRef.md
src/hooks/useImpressionRef/useImpressionRef.ts
src/hooks/useIntersectionObserver/useIntersectionObserver.md
src/hooks/useIntersectionObserver/useIntersectionObserver.ts
src/hooks/useIsomorphicLayoutEffect/useIsomorphicLayoutEffect.md
src/hooks/useIsomorphicLayoutEffect/useIsomorphicLayoutEffect.ts
src/hooks/usePrevious/usePrevious.md
src/hooks/usePrevious/usePrevious.ts
src/hooks/useRefEffect/useRefEffect.md
src/hooks/useRefEffect/useRefEffect.ts
src/hooks/useStorageState/useStorageState.md
src/hooks/useStorageState/useStorageState.ts
src/hooks/useThrottle/useThrottle.md
src/hooks/useThrottle/useThrottle.ts
src/hooks/useVisibilityEvent/useVisibilityEvent.md
src/hooks/useVisibilityEvent/useVisibilityEvent.ts

This PR standardizes the English documentation format for React hooks throughout the codebase. I've updated all English hook descriptions to follow a consistent pattern: "`[hookName]` is a React hook that..." followed by a clear explanation of its functionality and benefits.
The standardized format improves readability, makes the documentation more professional, and helps users quickly understand each hook's purpose. All technical details remain accurate while benefiting from a more consistent presentation style.

docs(eng): standardize React hook descriptions for consistency

---

src/components/ImpressionArea/ImpressionArea.tsx

In React versions below 18, it is not possible to pass a ref without using forwardRef.

fix: Apply forwardRef to ImpressionArea

---

src/utils/mergeProps/ko/mergeProps.md
src/utils/mergeProps/mergeProps.md

This pull request corrects the `mergeProps`' documentation where the variadic argument is represented as `props` instead of `...props`.
Current `mergeProps` function's implementation:
https://github.com/toss/react-simplikit/blob/94f8826353479d34aeba5f1479a2b831eb645ff7/src/utils/mergeProps/mergeProps.ts#L28
But current `mergeProps` documentation doesn't let readers know `props` argument is variable:
https://github.com/toss/react-simplikit/blob/94f8826353479d34aeba5f1479a2b831eb645ff7/src/utils/mergeProps/mergeProps.md?plain=1#L7-L11
So this pull request changes the above lines like following lines:
https://github.com/toss/react-simplikit/blob/ce3b5abe7486f088a349341f1ff8663a4594e12d/src/utils/mergeProps/ko/mergeProps.md?plain=1#L7-L11
- This pull request doesn't make changes about …

docs: fix mergeProps documentation to match actual implementation

---

src/hooks/useMap/index.ts
src/hooks/useMap/useMap.spec.ts
src/hooks/useMap/useMap.ts
src/index.ts

This PR adds a useMap hook that provides an efficient way to manage Map data structures in React components. The hook optimizes state updates and provides stable references to minimize unnecessary re-renders.
Key features:
- Efficient management of Map state (adding, updating, removing key-value pairs)
- Stable action functions to prevent unnecessary re-renders
- Initial state configuration and reset capability
- Full TypeScript type safety

feat(hooks): add 'useMap'

---

src/hooks/useInputState/ko/useInputState.md
src/hooks/useInputState/useInputState.md
src/hooks/useInputState/useInputState.spec.ts
src/hooks/useInputState/useInputState.ts

useInputState의 handleValueChange 의 반환 타입과 실제 사용 예제 코드가 알맞지 않아서, 타입 정의를 명확히 하고 handleValueChange 함수를 용도에 맞게 사용하도록 에제 코드도 수정하였습니다.

docs(useInputState): type re-definition
